title: David's Security Notes
theme: just-the-docs

url: https://david-gherghita.github.io

aux_links:
  Repository: https://github.com/david-gherghita/david-gherghita.github.io
  LinkedIn: https://www.linkedin.com/in/david-gherghita
aux_links_new_tab: true

color_scheme: dark
