title: David's Security Notes
theme: just-the-docs

url: https://david-gherghita.github.io

aux_links:
  Template Repository: https://github.com/david-gherghita/david-gherghita.github.io

color_scheme: dark
